- name: Install Fish shell
  homebrew:
    name: fish
  tags:
    - fish
    - install

- name: Install OH-MY-FISH
  shell: curl -L https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install -o /tmp/install | fish /tmp/install -y --offline --noninteractive
  tags:
    - fish
    - install

- name: Install OMF fzf plugin
  shell: /usr/bin/env fish -c omf install PatrickF1/fzf.fish
  tags:
    - fish
    - install

- name: Install OMF z plugin
  shell: /usr/bin/env fish -c omf install jethrokuan/z
  tags:
    - fish
    - install

- name: Install Starship
  homebrew:
    name: starship
  tags:
    - fish
    - install

