- name: Install Fish shell
  homebrew:
    name: fish
  tags:
    - fish
    - install

- name: Install OH-MY-FISH
  shell: curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install > /tmp/install | fish /tmp/install -y --noninteractive
  tags:
    - fish
    - install

# A hack to reload OMF variables
- name: Reload OMF
  shell: fish -c exit
  tags:
    - fish
    - install

- name: Install OMF fzf plugin
  shell: /usr/bin/env fish -c "omf install https://github.com/PatrickF1/fzf.fish"
  tags:
    - fish
    - install

- name: Install OMF z plugin
  shell: /usr/bin/env fish -c "omf install  https://github.com/jethrokuan/z"
  tags:
    - fish
    - install

- name: Install Starship
  homebrew:
    name: starship
  tags:
    - fish
    - install

